version: '3.8'

services:
  # Node.js app
  api:
    build: .
    ports:
      - "3000:3000"             # Map local port 3000 to container port 3000
    volumes:
      - .:/usr/src/app           # Mount the project directory to the container
      - /usr/src/app/node_modules # Avoid overwriting node_modules
    environment:
      - NODE_ENV=development     # Set environment variables
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    depends_on:
      - db                       # Ensure the MySQL service starts first
    command: npm run start         # Run the development server

  # MySQL database
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"              # Map local port 3306 to container port 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql   # Persist database data

volumes:
  db_data:                       # Volume for persistent MySQL data
